// <auto-generated />
using System;
using FinTrustFDManager.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinTrustFDManager.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.CoreData.CashFlow", b =>
                {
                    b.Property<int>("CashFlowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CashFlowId"));

                    b.Property<DateTime>("CashFlowDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CashFlowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InterestAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("InvestmentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("CashFlowId");

                    b.HasIndex("InvestmentId");

                    b.ToTable("CashFlows");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.CoreData.DayCountConvention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConventionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("DayCountConventions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConventionName = "30/360",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            ConventionName = "Actual/360",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            ConventionName = "Actual/365",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            ConventionName = "Actual/Actual",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.CoreData.InterestFrequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FrequencyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("InterestFrequencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FrequencyName = "Monthly",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            FrequencyName = "Quarterly",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            FrequencyName = "Half-Yearly",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            FrequencyName = "Annually",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            FrequencyName = "At Maturity",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.CoreData.Investment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("integer");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<int>("DayCountConventionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("InterestFrequencyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("numeric");

                    b.Property<string>("InvestmentReferenceNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DayCountConventionId");

                    b.HasIndex("EntityId");

                    b.HasIndex("InterestFrequencyId");

                    b.HasIndex("InvestmentReferenceNo")
                        .IsUnique();

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.CoreData.InvestmentApproval", b =>
                {
                    b.Property<int>("InvestmentApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvestmentApprovalId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ActionBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<int>("InvestmentId")
                        .HasColumnType("integer");

                    b.HasKey("InvestmentApprovalId");

                    b.HasIndex("InvestmentId");

                    b.ToTable("InvestmentApprovals");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.CounterParty", b =>
                {
                    b.Property<int>("CounterPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CounterPartyId"));

                    b.Property<string>("CounterPartyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CounterPartyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CounterPartyId");

                    b.HasIndex("CountryId");

                    b.ToTable("CounterParties");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.Currency", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CurrencyId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Symbol")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.Entity", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("EntityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.FDAmendment", b =>
                {
                    b.Property<long>("AmendmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AmendmentId"));

                    b.Property<string>("ApprovalComments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("ApprovedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FdId")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalValues")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long?>("RejectedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RejectedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionComments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("RequestedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedValues")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("AmendmentId");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("FdId", "Status");

                    b.ToTable("FDAmendments");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.FDApprovalHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("ActionBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("FdId")
                        .HasColumnType("bigint");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewValues")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("OldValues")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FdId", "ActionDate");

                    b.ToTable("FDApprovalHistories");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.Investment.FDCashFlow", b =>
                {
                    b.Property<long>("CashFlowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CashFlowId"));

                    b.Property<decimal>("CashFlowAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ClosingBalance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Days")
                        .HasColumnType("integer");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FdId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("InterestAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CashFlowId");

                    b.HasIndex("FdId");

                    b.ToTable("FDCashFlows");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.Investment.FDIdentification", b =>
                {
                    b.Property<long>("FdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FdId"));

                    b.Property<int?>("BankId")
                        .HasColumnType("integer");

                    b.Property<int>("CounterpartyId")
                        .HasColumnType("integer");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("FdReferenceNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("SettlementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("FdId");

                    b.HasIndex("BankId");

                    b.HasIndex("CounterpartyId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("EntityId");

                    b.HasIndex("FdReferenceNo")
                        .IsUnique();

                    b.ToTable("FDIdentifications");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.Investment.FDInterest", b =>
                {
                    b.Property<long>("FdInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FdInterestId"));

                    b.Property<int?>("BenchmarkId")
                        .HasColumnType("integer");

                    b.Property<string>("BenchmarkName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("BenchmarkRate")
                        .HasColumnType("numeric");

                    b.Property<int?>("CompoundingFrequencyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayCountConventionId")
                        .HasColumnType("integer");

                    b.Property<long>("FdId")
                        .HasColumnType("bigint");

                    b.Property<int>("InterestFrequencyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("numeric");

                    b.Property<string>("InterestRateType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsCompounding")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Margin")
                        .HasColumnType("numeric");

                    b.Property<string>("PaymentConvention")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("FdInterestId");

                    b.HasIndex("BenchmarkId");

                    b.HasIndex("CompoundingFrequencyId");

                    b.HasIndex("DayCountConventionId");

                    b.HasIndex("FdId")
                        .IsUnique();

                    b.HasIndex("InterestFrequencyId");

                    b.ToTable("FDInterests");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.MasterData.Bank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BankId"));

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BankId");

                    b.HasIndex("BankCode")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.MasterData.Benchmark", b =>
                {
                    b.Property<int>("BenchmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BenchmarkId"));

                    b.Property<string>("BenchmarkName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentRate")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RateUnit")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("BenchmarkId");

                    b.HasIndex("BenchmarkName")
                        .IsUnique();

                    b.ToTable("Benchmarks");

                    b.HasData(
                        new
                        {
                            BenchmarkId = 1,
                            BenchmarkName = "Repo Rate",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentRate = 6.50m,
                            Description = "Reserve Bank of India Repo Rate",
                            IsActive = true,
                            RateUnit = "%"
                        },
                        new
                        {
                            BenchmarkId = 2,
                            BenchmarkName = "LIBOR",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentRate = 5.50m,
                            Description = "London Interbank Offered Rate",
                            IsActive = true,
                            RateUnit = "%"
                        },
                        new
                        {
                            BenchmarkId = 3,
                            BenchmarkName = "MIBOR",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentRate = 6.25m,
                            Description = "Mumbai Interbank Offered Rate",
                            IsActive = true,
                            RateUnit = "%"
                        },
                        new
                        {
                            BenchmarkId = 4,
                            BenchmarkName = "T-Bill Rate",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentRate = 6.00m,
                            Description = "Treasury Bill Rate",
                            IsActive = true,
                            RateUnit = "%"
                        },
                        new
                        {
                            BenchmarkId = 5,
                            BenchmarkName = "SOFR",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentRate = 5.30m,
                            Description = "Secured Overnight Financing Rate",
                            IsActive = true,
                            RateUnit = "%"
                        });
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.MasterData.BenchmarkRateHistory", b =>
                {
                    b.Property<long>("BenchmarkRateHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BenchmarkRateHistoryId"));

                    b.Property<int>("BenchmarkId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.HasKey("BenchmarkRateHistoryId");

                    b.HasIndex("BenchmarkId");

                    b.ToTable("BenchmarkRateHistories");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.MasterData.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 8, 29, 14, 20, 8, 734, DateTimeKind.Utc).AddTicks(806),
                            IsActive = true,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 8, 29, 14, 20, 8, 734, DateTimeKind.Utc).AddTicks(809),
                            IsActive = true,
                            RoleName = "CA"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 8, 29, 14, 20, 8, 734, DateTimeKind.Utc).AddTicks(811),
                            IsActive = true,
                            RoleName = "Approver"
                        });
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.CoreData.CashFlow", b =>
                {
                    b.HasOne("FinTrustFDManager.Model.Entities.CoreData.Investment", "Investment")
                        .WithMany("CashFlows")
                        .HasForeignKey("InvestmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investment");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.CoreData.Investment", b =>
                {
                    b.HasOne("FinTrustFDManager.Model.Entities.MasterData.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinTrustFDManager.Model.Entities.MasterData.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinTrustFDManager.Model.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinTrustFDManager.Model.Entities.CoreData.DayCountConvention", "DayCountConvention")
                        .WithMany()
                        .HasForeignKey("DayCountConventionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinTrustFDManager.Model.Entities.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinTrustFDManager.Model.Entities.CoreData.InterestFrequency", "InterestFrequency")
                        .WithMany()
                        .HasForeignKey("InterestFrequencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Country");

                    b.Navigation("Currency");

                    b.Navigation("DayCountConvention");

                    b.Navigation("Entity");

                    b.Navigation("InterestFrequency");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.CoreData.InvestmentApproval", b =>
                {
                    b.HasOne("FinTrustFDManager.Model.Entities.CoreData.Investment", "Investment")
                        .WithMany("Approvals")
                        .HasForeignKey("InvestmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investment");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.CounterParty", b =>
                {
                    b.HasOne("FinTrustFDManager.Model.Entities.MasterData.Country", "Country")
                        .WithMany("CounterParties")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.Entity", b =>
                {
                    b.HasOne("FinTrustFDManager.Model.Entities.MasterData.Country", "Country")
                        .WithMany("Entities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.FDAmendment", b =>
                {
                    b.HasOne("FinTrustFDManager.Model.Entities.Investment.FDIdentification", null)
                        .WithMany()
                        .HasForeignKey("FdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.FDApprovalHistory", b =>
                {
                    b.HasOne("FinTrustFDManager.Model.Entities.Investment.FDIdentification", null)
                        .WithMany()
                        .HasForeignKey("FdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.Investment.FDCashFlow", b =>
                {
                    b.HasOne("FinTrustFDManager.Model.Entities.Investment.FDIdentification", null)
                        .WithMany()
                        .HasForeignKey("FdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.Investment.FDIdentification", b =>
                {
                    b.HasOne("FinTrustFDManager.Model.Entities.MasterData.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinTrustFDManager.Model.Entities.CounterParty", "CounterParty")
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinTrustFDManager.Model.Entities.Currency", "CurrencyNavigation")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinTrustFDManager.Model.Entities.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("CounterParty");

                    b.Navigation("CurrencyNavigation");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.Investment.FDInterest", b =>
                {
                    b.HasOne("FinTrustFDManager.Model.Entities.MasterData.Benchmark", "Benchmark")
                        .WithMany()
                        .HasForeignKey("BenchmarkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinTrustFDManager.Model.Entities.CoreData.InterestFrequency", "CompoundingFrequencyNavigation")
                        .WithMany()
                        .HasForeignKey("CompoundingFrequencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinTrustFDManager.Model.Entities.CoreData.DayCountConvention", "DayCountConvention")
                        .WithMany()
                        .HasForeignKey("DayCountConventionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinTrustFDManager.Model.Entities.Investment.FDIdentification", "FDIdentification")
                        .WithOne()
                        .HasForeignKey("FinTrustFDManager.Model.Entities.Investment.FDInterest", "FdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinTrustFDManager.Model.Entities.CoreData.InterestFrequency", "InterestFrequency")
                        .WithMany()
                        .HasForeignKey("InterestFrequencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Benchmark");

                    b.Navigation("CompoundingFrequencyNavigation");

                    b.Navigation("DayCountConvention");

                    b.Navigation("FDIdentification");

                    b.Navigation("InterestFrequency");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.MasterData.Bank", b =>
                {
                    b.HasOne("FinTrustFDManager.Model.Entities.MasterData.Country", "Country")
                        .WithMany("Banks")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.MasterData.BenchmarkRateHistory", b =>
                {
                    b.HasOne("FinTrustFDManager.Model.Entities.MasterData.Benchmark", "Benchmark")
                        .WithMany("RateHistory")
                        .HasForeignKey("BenchmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benchmark");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.User", b =>
                {
                    b.HasOne("FinTrustFDManager.Model.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.CoreData.Investment", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("CashFlows");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.MasterData.Benchmark", b =>
                {
                    b.Navigation("RateHistory");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.MasterData.Country", b =>
                {
                    b.Navigation("Banks");

                    b.Navigation("CounterParties");

                    b.Navigation("Entities");
                });

            modelBuilder.Entity("FinTrustFDManager.Model.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
